# Generated by Django 3.1.4 on 2021-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_nonteachingstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('readmore', models.URLField(max_length=100)),
            ],
        ),
    ]
